const W9={ex1:0,wood:0};
const $9=id=>document.getElementById(id); const n9=id=>Number($9(id)?.value||0);
function t9(id,txt){const e=$9(id); if(e)e.textContent=txt}
function html9(id,txt){const e=$9(id); if(e){e.innerHTML=txt; renderMath(e)}}
function setW9Matter(state='liquid'){
 const g=$9('w9Particles'); if(!g)return; let pts=[]; let text='';
 if(state==='solid'){for(let r=0;r<4;r++)for(let c=0;c<9;c++)pts.push([170+c*62,85+r*42]); text='ของแข็ง: อนุภาคเรียงตัวค่อนข้างเป็นระเบียบและเคลื่อนที่ได้น้อย';}
 if(state==='liquid'){for(let i=0;i<36;i++)pts.push([140+(i%9)*70+(i%2)*8,135+Math.floor(i/9)*32+((i*17)%11)]); text='ของเหลว: อนุภาคอยู่ชิดกันแต่เลื่อนไหลผ่านกันได้ จึงเปลี่ยนรูปร่างตามภาชนะ';}
 if(state==='gas'){for(let i=0;i<30;i++)pts.push([90+((i*97)%720),65+((i*53)%170)]); text='ก๊าซ: อนุภาคกระจายตัวมาก เคลื่อนที่อิสระ และเติมเต็มภาชนะ';}
 g.innerHTML=pts.map((p,i)=>`<circle class="w9-particle" cx="${p[0]}" cy="${p[1]}" r="13" fill="${state==='gas'?'#fbbf24':state==='liquid'?'#38bdf8':'#94a3b8'}" stroke="#334155"><title>particle ${i+1}</title></circle>`).join('');
 t9('w9MatterFeedback',text);
}
function updateW9Ideal(){const checks=[...document.querySelectorAll('.w9Ideal')]; const ok=checks.every(c=>c.checked); const e=$9('w9IdealFeedback'); if(!e)return; e.textContent=ok?'ครบ 3 เงื่อนไข: ใช้เป็นแบบจำลองของไหลอุดมคติได้':'ยังไม่ครบเงื่อนไขของของไหลอุดมคติ'; e.className=ok?'good':'bad'}
function updateW9Pressure(){const F=n9('w9F'),A=n9('w9A'),P=F/A; t9('w9FVal',F.toFixed(0)); t9('w9AVal',A.toFixed(2)); const w=Math.max(35,Math.min(260,A*260)); const b=$9('w9AreaBlock'); if(b){b.setAttribute('width',w); b.setAttribute('x',250-w/2)} html9('w9PressureFeedback',`\\[P=\\frac{${F.toFixed(0)}}{${A.toFixed(2)}}=${P.toFixed(0)}\\ \\mathrm{Pa}\\]`)}
function updateW9Density(){const m=n9('w9Mass'),V=n9('w9Vol'),rho=m/V; t9('w9MassVal',m.toFixed(1)); t9('w9VolVal',V.toFixed(3)); html9('w9DensityFeedback',`\\[\\rho=\\frac{${m.toFixed(1)}}{${V.toFixed(3)}}=${rho.toFixed(0)}\\ \\mathrm{kg/m^3}\\] ${rho>1000?'ความหนาแน่นมากกว่าน้ำ':'ความหนาแน่นน้อยกว่าหรือใกล้เคียงน้ำ'}`)}
function updateW9Hydro(){const h=n9('w9Depth'),rho=n9('w9Rho'),g=n9('w9G'),Pg=rho*g*h,Pa=101325+Pg; t9('w9DepthVal',h.toFixed(1)); t9('w9RhoVal',rho.toFixed(0)); t9('w9GVal',g.toFixed(2)); const y=90+(h/10)*290; const p=$9('w9DepthPoint'),l=$9('w9DepthLine'),lab=$9('w9DepthLabel'); if(p)p.setAttribute('cy',y); if(l)l.setAttribute('y2',y); if(lab)lab.setAttribute('y',(90+y)/2); html9('w9HydroFeedback',`\\[P_g=\\rho gh=${(Pg/1000).toFixed(2)}\\ \\mathrm{kPa},\\quad P_{abs}=${(Pa/1000).toFixed(2)}\\ \\mathrm{kPa}\\]`)}
function updateW9Layered(){const h1=n9('w9H1'),h2=n9('w9H2'),h3=n9('w9H3'),g=9.81; t9('w9H1Val',h1.toFixed(1));t9('w9H2Val',h2.toFixed(1));t9('w9H3Val',h3.toFixed(2)); const Pg=(800*h1+1000*h2+13600*h3)*g; html9('w9LayerFeedback',`\\[P_g=g(800h_1+1000h_2+13600h_3)=${(Pg/1000).toFixed(2)}\\ \\mathrm{kPa}\\]`); const total=Math.max(.1,h1+h2+h3), H=270, base=340; const segs=[['น้ำมัน',h1,'#fde68a'],['น้ำ',h2,'#7dd3fc'],['ปรอท',h3,'#94a3b8']]; let y=base,out=''; segs.forEach(([name,h,c])=>{const hh=H*h/total; y-=hh; if(h>0)out+=`<rect x="152" y="${y}" width="196" height="${hh}" fill="${c}"/><text x="250" y="${y+hh/2}" text-anchor="middle" fill="#334155">${name}</text>`}); const gEl=$9('w9LayerVisual'); if(gEl)gEl.innerHTML=out;}
function nextW9Step(which){W9[which]=(W9[which]||0)+1; renderW9Step(which)} function resetW9Step(which){W9[which]=0; renderW9Step(which)}
function renderW9Step(which){const ex1=[`<p><strong>1.</strong> ข้อมูล: \\(h=2.0\\,\\mathrm{m},\\rho=1000\\,\\mathrm{kg/m^3},g=9.81\\,\\mathrm{m/s^2}\\)</p>`,`<p><strong>2.</strong> ความดันเกจ: \\(P_g=\\rho gh\\)</p>`,`<p><strong>3.</strong> แทนค่า: \\(P_g=(1000)(9.81)(2.0)=1.962\\times10^4\\,\\mathrm{Pa}=19.6\\,\\mathrm{kPa}\\)</p>`,`<p><strong>4.</strong> ความดันสมบูรณ์: \\(P_{abs}=P_{atm}+P_g=101.3+19.6=120.9\\,\\mathrm{kPa}\\)</p>`]; const wood=[`<p><strong>1.</strong> วัตถุลอยนิ่ง ดังนั้น \\(F_B=W=mg\\)</p>`,`<p><strong>2.</strong> \\(\\rho_w g V_{sub}=mg\\Rightarrow V_{sub}=m/\\rho_w=4.0/1000=0.004\\,\\mathrm{m^3}\\)</p>`,`<p><strong>3.</strong> พื้นที่ฐานแท่งไม้ \\(A=0.30\\times0.20=0.060\\,\\mathrm{m^2}\\)</p>`,`<p><strong>4.</strong> ความลึกส่วนที่จม \\(h_{sub}=V_{sub}/A=0.004/0.060=0.067\\,\\mathrm{m}=6.7\\,\\mathrm{cm}\\)</p>`,`<p><strong>5.</strong> แรงลอยตัว \\(F_B=mg=(4.0)(9.81)\\approx39\\,\\mathrm{N}\\)</p>`]; const arr=which==='wood'?wood:ex1; const id=which==='wood'?'w9WoodSteps':'w9Ex1Steps'; html9(id,arr.slice(0,W9[which]).join('') || '<p>กด “แสดงขั้นต่อไป” เพื่อเริ่มเฉลย</p>')}
function updateW9BottomForce(){const d=n9('w9D')/100,h=n9('w9TankH'),A=Math.PI*d*d/4,P=101325+1000*9.81*h,F=P*A;t9('w9DVal',(d*100).toFixed(1));t9('w9TankHVal',h.toFixed(1));html9('w9BottomForceFeedback',`\\[A=${A.toFixed(4)}\\,\\mathrm{m^2},\\quad F=P_{abs}A=${F.toFixed(0)}\\,\\mathrm{N}\\]`)}
function updateW9Barometer(){const hmm=n9('w9HgH'),P=13600*9.81*(hmm/1000); t9('w9HgHVal',hmm.toFixed(0)); html9('w9BarometerFeedback',`\\[P_{atm}=\\rho gh=${P.toFixed(0)}\\ \\mathrm{Pa}\\]`)}
function updateW9Manometer(){const hcm=n9('w9ManoH'),P=101325+13600*9.81*(hcm/100); t9('w9ManoHVal',hcm.toFixed(0)); html9('w9ManometerFeedback',`\\[P_{gas}=P_{atm}+\\rho gh=${(P/1000).toFixed(2)}\\ \\mathrm{kPa}\\]`)}
function pulseW9Pascal(){const dots=$9('w9PressureDots'),p=$9('w9PistonSmall'); if(!dots)return; let out=''; for(let i=0;i<28;i++)out+=`<circle cx="${165+(i%14)*45}" cy="${150+Math.floor(i/14)*45}" r="8" fill="#2563eb" opacity=".75"/>`; dots.innerHTML=out; dots.classList.remove('w9Pulse'); void dots.offsetWidth; dots.classList.add('w9Pulse'); p?.classList.add('w9PistonDown'); setTimeout(()=>p?.classList.remove('w9PistonDown'),350)}
function updateW9Hydraulic(){const F1=n9('w9F1'),d1=n9('w9D1'),d2=n9('w9D2'),ratio=(d2/d1)**2,F2=F1*ratio; t9('w9F1Val',F1.toFixed(0));t9('w9D1Val',d1.toFixed(1));t9('w9D2Val',d2.toFixed(1)); const bp=$9('w9BigPiston'); if(bp)bp.setAttribute('y',Math.max(40,105-Math.min(60,ratio/4))); html9('w9HydraulicFeedback',`\\[\\frac{A_2}{A_1}=\\left(\\frac{d_2}{d_1}\\right)^2=${ratio.toFixed(1)},\\quad F_2=${F2.toFixed(0)}\\ \\mathrm{N}\\]`)}
function updateW9Buoyancy(){const V=n9('w9Vdisp'),rho=n9('w9FluidRho'),m=n9('w9ObjMass'),FB=rho*9.81*V,W=m*9.81; t9('w9VdispVal',V.toFixed(3));t9('w9FluidRhoVal',rho.toFixed(0));t9('w9ObjMassVal',m.toFixed(1)); const status=FB>W?'วัตถุมีแนวโน้มลอยขึ้น':Math.abs(FB-W)<1?'วัตถุสมดุล':'วัตถุมีแนวโน้มจมลง'; const block=$9('w9FloatBlock'); if(block)block.setAttribute('y',FB>=W?130:190); html9('w9BuoyancyFeedback',`\\[F_B=${FB.toFixed(1)}\\,\\mathrm{N},\\quad W=${W.toFixed(1)}\\,\\mathrm{N}\\] ${status}`)}
document.addEventListener('DOMContentLoaded',()=>{setW9Matter('liquid');updateW9Ideal();updateW9Pressure();updateW9Density();updateW9Hydro();updateW9Layered();renderW9Step('ex1');renderW9Step('wood');updateW9BottomForce();updateW9Barometer();updateW9Manometer();pulseW9Pascal();updateW9Hydraulic();updateW9Buoyancy();});
